import React, { useEffect, useMemo, useState } from 'react';
import { loadTenders, refreshTenders } from './services/tenderSource.js';
import { getTenderMatchReasons } from './services/tenderMatching.js';
import { getSession, subscribeToAuth, loadAccountData, saveProfile, setTenderSaved, signOut } from './services/account.js';
import { analyzeTender } from './services/analysis.js';
import { createCheckoutSession, openCustomerPortal } from './services/billing.js';
import { isSupabaseConfigured } from './lib/supabase.js';
import AuthGate from './components/AuthGate.jsx';

const sectors=['IT & Telecom','Construction','Facilities','Electrical','IT & Software'];
const sizes=['Under OMR 100k','OMR 100k–300k','OMR 300k+'];

export default function App(){
 const [session,setSession]=useState(undefined); const [view,setView]=useState('dashboard');
 const [profile,setProfile]=useState({company:'',sectors:[],locations:['Muscat'],size:'OMR 100k–300k'});
 const [saved,setSaved]=useState([]); const [subscription,setSubscription]=useState(null); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [selected,setSelected]=useState(null);
 const [tenders,setTenders]=useState([]); const [source,setSource]=useState({label:'Loading…'}); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [accountLoading,setAccountLoading]=useState(isSupabaseConfigured);
 const [billingMessage,setBillingMessage]=useState('');
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const billing=params.get('billing');if(billing==='success')setBillingMessage('Payment successful. Your subscription will appear here after Stripe confirms it.');if(billing==='cancelled')setBillingMessage('Checkout was cancelled. No subscription changes were made.');if(billing)window.history.replaceState({},'',window.location.pathname);},[]);
 useEffect(()=>{ if(!isSupabaseConfigured){setSession(null);setAccountLoading(false);return;} let active=true; getSession().then(s=>{if(active){setSession(s);setAccountLoading(false)}}); return subscribeToAuth(s=>{setSession(s);setAccountLoading(false)}); },[]);
 useEffect(()=>{let mounted=true;loadTenders().then(r=>{if(mounted){setTenders(r.tenders);setSource(r);setLoading(false)}}).catch(()=>mounted&&setLoading(false));return()=>{mounted=false}},[]);
 useEffect(()=>{if(!session?.user?.id)return; loadAccountData(session.user.id).then(({profile:p,saved:s,subscription:sub})=>{if(p)setProfile({company:p.company_name||'',sectors:p.sectors||[],locations:p.locations?.length?p.locations:['Muscat'],size:p.contract_size||'OMR 100k–300k'});setSaved(s);setSubscription(sub||null)}).catch(console.error)},[session]);
 const results=useMemo(()=>tenders.filter(t=>(filter==='All'||t.category===filter||t.location===filter)&&(`${t.title} ${t.authority} ${t.category} ${t.location}`.toLowerCase().includes(query.toLowerCase()))),[tenders,query,filter]);
 const toggleSaved=async id=>{const next=!saved.includes(id);setSaved(s=>next?[...s,id]:s.filter(x=>x!==id));if(session)try{await setTenderSaved(session.user.id,id,next)}catch(e){console.error(e);setSaved(s=>next?s.filter(x=>x!==id):[...s,id])}};
 const persistProfile=async()=>{if(session)try{await saveProfile(session.user.id,profile);setLoading(true);const r=await loadTenders();setTenders(r.tenders);setSource(r)}catch(e){console.error(e)}finally{setLoading(false)}setView('dashboard')};
 const handleRefresh=async()=>{if(refreshing)return;setRefreshing(true);try{const r=await refreshTenders();setTenders(r.tenders);setSource(r)}catch(e){setSource(s=>({...s,error:e?.message||'Tender refresh failed.'}))}finally{setRefreshing(false)}};
 if(accountLoading)return <div className="authGate"><div className="authCard"><h1>Loading workspace…</h1></div></div>;
 if(isSupabaseConfigured&&!session)return <AuthGate onAuthenticated={setSession}/>;
 return <div className="shell"><aside className="side"><div className="sideBrand"><span className="mark">OT</span><span>Oman Tender<br/><b>Intelligence</b></span></div><div className="sideNav">{['dashboard','tenders','saved','profile'].map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{({dashboard:'⌂ Dashboard',tenders:'⌕ Tender Feed',saved:'☆ Saved Tenders',profile:'◉ Company Profile'})[x]}</button>)}</div><div className="sideBottom"><small>DATA SOURCE</small><strong>{source.label}</strong><span>{saved.length} saved tenders</span><button onClick={()=>setView('pricing')}>{subscription?.plan&&subscription.plan!=='free'?`Plan: ${subscription.plan}`:'Upgrade plan'} →</button></div></aside>
 <main className="main"><header className="top"><span className="mobileBrand">Oman Tender Intelligence</span><div className="user"><span>{profile.company||session?.user?.email||'Your Company'}</span>{session&&<button className="textBtn" onClick={()=>signOut().catch(console.error)}>Sign out</button>}<b>OT</b></div></header>
 {billingMessage&&<div className="billingNotice">{billingMessage}</div>}
 {view==='dashboard'&&<Dashboard tenders={tenders} profile={profile} saved={saved} setView={setView} toggleSaved={toggleSaved} setSelected={setSelected} loading={loading} source={source} onRefresh={handleRefresh} refreshing={refreshing}/>} 
 {view==='tenders'&&<TenderFeed results={results} profile={profile} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} saved={saved} toggleSaved={toggleSaved} setSelected={setSelected} loading={loading} onRefresh={handleRefresh} refreshing={refreshing}/>} 
 {view==='saved'&&<Saved tenders={tenders.filter(t=>saved.includes(t.id))} profile={profile} toggleSaved={toggleSaved} setSelected={setSelected} setView={setView}/>} 
 {view==='profile'&&<Profile profile={profile} setProfile={setProfile} setView={setView} onSave={persistProfile}/>} {view==='pricing'&&<Pricing subscription={subscription}/>}</main>{selected&&<TenderModal tender={selected} close={()=>setSelected(null)} saved={saved.includes(selected.id)} toggleSaved={toggleSaved}/>}</div>
}
function Dashboard({tenders,profile,saved,setView,toggleSaved,setSelected,loading,source,onRefresh,refreshing}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">GOOD MORNING</span><h1>Your tender pipeline</h1><p>High-fit Oman opportunities, ranked for your business.</p></div><div className="pageActions"><button className="outline" disabled={refreshing} onClick={onRefresh}>{refreshing?'Refreshing…':'↻ Refresh tenders'}</button><button className="primary" onClick={()=>setView('tenders')}>Explore tenders →</button></div></div>{source.error&&<div className="sourceNotice">Live source refresh failed — showing the latest cached tenders.</div>}<div className="metrics"><Metric n={loading?'—':tenders.length} label="Open tenders"/><Metric n={loading?'—':tenders.filter(t=>t.score>=90).length} label="High-fit matches"/><Metric n={saved.length} label="Saved"/><Metric n="3" label="Deadlines this week"/></div><div className="panel"><div className="panelHead"><div><h2>Recommended for you</h2><p>Based on your company profile</p></div><button className="textBtn" onClick={()=>setView('tenders')}>View all →</button></div>{loading?<div className="empty">Loading tender opportunities…</div>:tenders.slice(0,4).map(t=><TenderRow key={t.id} t={t} profile={profile} saved={saved.includes(t.id)} toggleSaved={toggleSaved} setSelected={setSelected}/>)}</div><div className="tip"><span>✦</span><div><strong>Make your matches smarter</strong><p>Complete your company profile with sectors and capabilities to improve relevance scoring.</p></div><button onClick={()=>setView('profile')}>Complete profile →</button></div></div>}
function Metric({n,label}){return <div className="metric"><strong>{n}</strong><span>{label}</span></div>}
function TenderRow({t,profile,saved,toggleSaved,setSelected}){const reasons=getTenderMatchReasons(t,profile);return <div className="trow"><div className="score">{t.score}<small>%</small><span>MATCH</span></div><div className="tinfo"><button className="titleBtn" onClick={()=>setSelected(t)}>{t.title}</button><div>{t.authority} · {t.category} · {t.location}</div>{reasons.length>0&&<div className="matchReasons">{reasons.map(r=><span key={r}>✓ {r}</span>)}</div>}</div><div className="tvalue"><strong>{t.value}</strong><span>Deadline {t.deadline}</span></div><button className={'save '+(saved?'saved':'')} onClick={()=>toggleSaved(t.id)}>{saved?'★':'☆'}</button></div>}
function TenderFeed({results,profile,query,setQuery,filter,setFilter,saved,toggleSaved,setSelected,loading,onRefresh,refreshing}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">TENDER INTELLIGENCE</span><h1>Find your next opportunity</h1><p>Search and filter Oman tenders in one workspace.</p></div><button className="outline" disabled={refreshing} onClick={onRefresh}>{refreshing?'Refreshing…':'↻ Refresh tenders'}</button></div><div className="searchbar"><input placeholder="Search tenders, authorities, categories…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{sectors.map(s=><option key={s}>{s}</option>)}<option>Muscat</option><option>Sohar</option><option>Salalah</option></select></div><div className="panel"><div className="panelHead"><div><h2>{loading?'Loading…':`${results.length} opportunities`}</h2><p>Sorted by relevance to your profile</p></div></div>{!loading&&results.map(t=><TenderRow key={t.id} t={t} profile={profile} saved={saved.includes(t.id)} toggleSaved={toggleSaved} setSelected={setSelected}/>)}</div></div>}
function Saved({tenders,profile,toggleSaved,setSelected,setView}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">WATCHLIST</span><h1>Saved tenders</h1><p>Keep your best opportunities in one place.</p></div></div><div className="panel">{tenders.length?tenders.map(t=><TenderRow key={t.id} t={t} profile={profile} saved toggleSaved={toggleSaved} setSelected={setSelected}/>):<div className="empty">No saved tenders yet.<button className="primary" onClick={()=>setView('tenders')}>Browse tender feed →</button></div>}</div></div>}
function Profile({profile,setProfile,setView,onSave}){const update=(k,v)=>setProfile({...profile,[k]:v});const toggle=s=>update('sectors',profile.sectors.includes(s)?profile.sectors.filter(x=>x!==s):[...profile.sectors,s]);return <div className="content"><div className="pageTitle"><div><span className="eyebrow">COMPANY PROFILE</span><h1>Tell us what you bid for</h1><p>Your profile powers personalized tender matching.</p></div></div><div className="formPanel"><label>Company name<input value={profile.company} onChange={e=>update('company',e.target.value)} placeholder="e.g. ABC Trading LLC"/></label><label>Primary sectors<div className="chips">{sectors.map(s=><button className={profile.sectors.includes(s)?'chip on':'chip'} onClick={()=>toggle(s)} key={s}>{s}</button>)}</div></label><label>Preferred locations<div className="chips">{['Muscat','Sohar','Salalah'].map(s=><button className={profile.locations.includes(s)?'chip on':'chip'} onClick={()=>update('locations',profile.locations.includes(s)?profile.locations.filter(x=>x!==s):[...profile.locations,s])} key={s}>{s}</button>)}</div></label><label>Typical contract size<div className="chips">{sizes.map(s=><button className={profile.size===s?'chip on':'chip'} onClick={()=>update('size',s)} key={s}>{s}</button>)}</div></label><button className="primary big" onClick={onSave}>Save company profile →</button></div></div>}
function Pricing({subscription}){const [busy,setBusy]=useState('');const [error,setError]=useState('');const choose=async plan=>{setBusy(plan);setError('');try{await createCheckoutSession(plan)}catch(e){setError(e?.message||'Checkout could not be started.');setBusy('')}};const manage=async()=>{setBusy('portal');setError('');try{await openCustomerPortal()}catch(e){setError(e?.message||'Customer portal could not be opened.');setBusy('')}};return <div className="content"><div className="pageTitle"><div><span className="eyebrow">UPGRADE</span><h1>Choose the intelligence level you need</h1><p>{subscription?.plan&&subscription.plan!=='free'?`Current plan: ${subscription.plan}. Manage your subscription from your Stripe customer portal.`:'Start free and unlock deeper analysis as your bid pipeline grows.'}</p></div>{subscription?.plan&&subscription.plan!=='free'&&<button className="outline" disabled={busy==='portal'} onClick={manage}>{busy==='portal'?'Opening portal…':'Manage subscription'}</button>}</div>{error&&<div className="sourceNotice">{error}</div>}<div className="upgradeGrid">{[['Starter','OMR 9','starter',['Full tender search','Email deadline alerts','25 AI analyses/month']],['Pro','OMR 25','pro',['AI summaries','Eligibility analysis','100 AI analyses/month','Personalized match score']],['Business','OMR 59','business',['Everything in Pro','500 AI analyses/month','Exports & reports','Team workspace']]].map(([n,p,plan,f])=><div className={n==='Pro'?'upgrade featured':'upgrade'} key={n}><h3>{n}</h3><div className="upgradePrice">{p}<small>/month</small></div><ul>{f.map(x=><li key={x}>✓ {x}</li>)}</ul><button className={n==='Pro'?'primary':'outline'} disabled={busy===plan||subscription?.plan===plan} onClick={()=>choose(plan)}>{subscription?.plan===plan?'Current plan':busy===plan?'Opening checkout…':`Choose ${n}`}</button></div>)}</div></div>}
function TenderModal({tender,close,saved,toggleSaved}){const [analysis,setAnalysis]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const runAnalysis=async()=>{setBusy(true);setError('');try{const result=await analyzeTender(tender);setAnalysis(result)}catch(e){setError(e?.code==='USAGE_LIMIT'?`Analysis limit reached (${e.used}/${e.limit}). Upgrade your plan for more analyses.`:(e.message||'Analysis failed.'))}finally{setBusy(false)}};return <div className="overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className="eyebrow">{tender.category.toUpperCase()}</span><h2>{tender.title}</h2><p className="modalAuthority">{tender.authority} · {tender.location}</p><div className="modalStats"><div><small>MATCH SCORE</small><strong>{analysis?.analysis?.fitScore ?? tender.score}%</strong></div><div><small>EST. VALUE</small><strong>{tender.value}</strong></div><div><small>DEADLINE</small><strong>{tender.deadline}</strong></div></div><h3>{analysis?'AI opportunity analysis':'Opportunity brief'}</h3><p>{analysis?.analysis?.summary || tender.summary}</p>{analysis&&<><h3>Strengths</h3><ul>{analysis.analysis.strengths.map(x=><li key={x}>{x}</li>)}</ul><h3>Risks</h3><ul>{analysis.analysis.risks.map(x=><li key={x}>{x}</li>)}</ul></>} {error&&<div className="sourceNotice">{error}</div>}<h3>Key signals</h3><div className="chips">{tender.tags.map(x=><span className="chip on" key={x}>{x}</span>)}</div><div className="modalActions"><button className="outline" onClick={()=>toggleSaved(tender.id)}>{saved?'★ Saved':'☆ Save tender'}</button><button className="primary" disabled={busy} onClick={runAnalysis}>{busy?'Analyzing…':analysis?'Re-analyze tender →':'Analyze tender →'}</button></div></div></div>}
