import React, { useEffect, useMemo, useState } from 'react';
import { loadTenders } from './services/tenderSource.js';

const sectors = ['IT & Telecom','Construction','Facilities','Electrical','IT & Software'];
const sizes = ['Under OMR 100k','OMR 100k–300k','OMR 300k+'];

export default function App(){
  const [view,setView]=useState('dashboard');
  const [profile,setProfile]=useState({company:'',sectors:[],locations:['Muscat'],size:'OMR 100k–300k'});
  const [saved,setSaved]=useState([]); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [selected,setSelected]=useState(null);
  const [tenders,setTenders]=useState([]); const [source,setSource]=useState({label:'Loading…'}); const [loading,setLoading]=useState(true);
  useEffect(()=>{let mounted=true;loadTenders().then(r=>{if(!mounted)return;setTenders(r.tenders);setSource(r);setLoading(false)}).catch(()=>mounted&&setLoading(false));return()=>{mounted=false}},[]);
  const results=useMemo(()=>tenders.filter(t=>(filter==='All'||t.category===filter||t.location===filter)&&(`${t.title} ${t.authority} ${t.category} ${t.location}`.toLowerCase().includes(query.toLowerCase()))),[tenders,query,filter]);
  const toggleSaved=id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
  return <div className="shell"><aside className="side"><div className="sideBrand"><span className="mark">OT</span><span>Oman Tender<br/><b>Intelligence</b></span></div><div className="sideNav">{['dashboard','tenders','saved','profile'].map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{({dashboard:'⌂ Dashboard',tenders:'⌕ Tender Feed',saved:'☆ Saved Tenders',profile:'◉ Company Profile'})[x]}</button>)}</div><div className="sideBottom"><small>DATA SOURCE</small><strong>{source.label}</strong><span>{saved.length}/5 saved tenders</span><button onClick={()=>setView('pricing')}>Upgrade plan →</button></div></aside>
  <main className="main"><header className="top"><span className="mobileBrand">Oman Tender Intelligence</span><div className="user"><span>{profile.company||'Your Company'}</span><b>JD</b></div></header>
  {view==='dashboard'&&<Dashboard tenders={tenders} saved={saved} setView={setView} toggleSaved={toggleSaved} setSelected={setSelected} loading={loading} source={source}/>} {view==='tenders'&&<TenderFeed results={results} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} saved={saved} toggleSaved={toggleSaved} setSelected={setSelected} loading={loading}/>} {view==='saved'&&<Saved tenders={tenders.filter(t=>saved.includes(t.id))} toggleSaved={toggleSaved} setSelected={setSelected} setView={setView}/>} {view==='profile'&&<Profile profile={profile} setProfile={setProfile} setView={setView}/>} {view==='pricing'&&<Pricing/>}</main>{selected&&<TenderModal tender={selected} close={()=>setSelected(null)} saved={saved.includes(selected.id)} toggleSaved={toggleSaved}/>}</div>
}
function Dashboard({tenders,saved,setView,toggleSaved,setSelected,loading,source}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">GOOD MORNING</span><h1>Your tender pipeline</h1><p>High-fit Oman opportunities, ranked for your business.</p></div><button className="primary" onClick={()=>setView('tenders')}>Explore tenders →</button></div>{source.error&&<div className="sourceNotice">Live source unavailable — showing safe demo fallback.</div>}<div className="metrics"><Metric n={loading?'—':tenders.length} label="Open tenders"/><Metric n={loading?'—':tenders.filter(t=>t.score>=90).length} label="High-fit matches"/><Metric n={saved.length} label="Saved"/><Metric n="3" label="Deadlines this week"/></div><div className="panel"><div className="panelHead"><div><h2>Recommended for you</h2><p>Based on your company profile</p></div><button className="textBtn" onClick={()=>setView('tenders')}>View all →</button></div>{loading?<div className="empty">Loading tender opportunities…</div>:tenders.slice(0,4).map(t=><TenderRow key={t.id} t={t} saved={saved.includes(t.id)} toggleSaved={toggleSaved} setSelected={setSelected}/>)}</div><div className="tip"><span>✦</span><div><strong>Make your matches smarter</strong><p>Complete your company profile with sectors and capabilities to improve relevance scoring.</p></div><button onClick={()=>setView('profile')}>Complete profile →</button></div></div>}
function Metric({n,label}){return <div className="metric"><strong>{n}</strong><span>{label}</span></div>}
function TenderRow({t,saved,toggleSaved,setSelected}){return <div className="trow"><div className="score">{t.score}<small>%</small><span>MATCH</span></div><div className="tinfo"><button className="titleBtn" onClick={()=>setSelected(t)}>{t.title}</button><div>{t.authority} · {t.category} · {t.location}</div></div><div className="tvalue"><strong>{t.value}</strong><span>Deadline {t.deadline}</span></div><button className={'save '+(saved?'saved':'')} onClick={()=>toggleSaved(t.id)}>{saved?'★':'☆'}</button></div>}
function TenderFeed({results,query,setQuery,filter,setFilter,saved,toggleSaved,setSelected,loading}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">TENDER INTELLIGENCE</span><h1>Find your next opportunity</h1><p>Search and filter Oman tenders in one workspace.</p></div></div><div className="searchbar"><input placeholder="Search tenders, authorities, categories…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{sectors.map(s=><option key={s}>{s}</option>)}<option>Muscat</option><option>Sohar</option><option>Salalah</option></select></div><div className="panel"><div className="panelHead"><div><h2>{loading?'Loading…':`${results.length} opportunities`}</h2><p>Sorted by relevance to your profile</p></div></div>{!loading&&results.map(t=><TenderRow key={t.id} t={t} saved={saved.includes(t.id)} toggleSaved={toggleSaved} setSelected={setSelected}/>)}</div></div>}
function Saved({tenders,toggleSaved,setSelected,setView}){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">WATCHLIST</span><h1>Saved tenders</h1><p>Keep your best opportunities in one place.</p></div></div><div className="panel">{tenders.length?tenders.map(t=><TenderRow key={t.id} t={t} saved toggleSaved={toggleSaved} setSelected={setSelected}/>):<div className="empty">No saved tenders yet.<button className="primary" onClick={()=>setView('tenders')}>Browse tender feed →</button></div>}</div></div>}
function Profile({profile,setProfile,setView}){const update=(k,v)=>setProfile({...profile,[k]:v});const toggle=s=>update('sectors',profile.sectors.includes(s)?profile.sectors.filter(x=>x!==s):[...profile.sectors,s]);return <div className="content"><div className="pageTitle"><div><span className="eyebrow">COMPANY PROFILE</span><h1>Tell us what you bid for</h1><p>Your profile powers personalized tender matching.</p></div></div><div className="formPanel"><label>Company name<input value={profile.company} onChange={e=>update('company',e.target.value)} placeholder="e.g. ABC Trading LLC"/></label><label>Primary sectors<div className="chips">{sectors.map(s=><button className={profile.sectors.includes(s)?'chip on':'chip'} onClick={()=>toggle(s)} key={s}>{s}</button>)}</div></label><label>Preferred locations<div className="chips">{['Muscat','Sohar','Salalah'].map(s=><button className={profile.locations.includes(s)?'chip on':'chip'} onClick={()=>update('locations',profile.locations.includes(s)?profile.locations.filter(x=>x!==s):[...profile.locations,s])} key={s}>{s}</button>)}</div></label><label>Typical contract size<div className="chips">{sizes.map(s=><button className={profile.size===s?'chip on':'chip'} onClick={()=>update('size',s)} key={s}>{s}</button>)}</div></label><button className="primary big" onClick={()=>setView('dashboard')}>Save company profile →</button></div></div>}
function Pricing(){return <div className="content"><div className="pageTitle"><div><span className="eyebrow">UPGRADE</span><h1>Choose the intelligence level you need</h1><p>Start free and unlock deeper analysis as your bid pipeline grows.</p></div></div><div className="upgradeGrid">{[['Starter','OMR 9',['Full tender search','Email deadline alerts','50 saved tenders']],['Pro','OMR 25',['AI summaries','Eligibility analysis','Personalized match score','Unlimited saved tenders']],['Business','OMR 59',['Everything in Pro','10 users','Exports & reports','Team workspace']]].map(([n,p,f])=><div className={n==='Pro'?'upgrade featured':'upgrade'} key={n}><h3>{n}</h3><div className="upgradePrice">{p}<small>/month</small></div><ul>{f.map(x=><li key={x}>✓ {x}</li>)}</ul><button className={n==='Pro'?'primary':'outline'}>Choose {n}</button></div>)}</div></div>}
function TenderModal({tender,close,saved,toggleSaved}){return <div className="overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className="eyebrow">{tender.category.toUpperCase()}</span><h2>{tender.title}</h2><p className="modalAuthority">{tender.authority} · {tender.location}</p><div className="modalStats"><div><small>MATCH SCORE</small><strong>{tender.score}%</strong></div><div><small>EST. VALUE</small><strong>{tender.value}</strong></div><div><small>DEADLINE</small><strong>{tender.deadline}</strong></div></div><h3>AI opportunity brief</h3><p>{tender.summary}</p><h3>Key signals</h3><div className="chips">{tender.tags.map(x=><span className="chip on" key={x}>{x}</span>)}</div><div className="modalActions"><button className="outline" onClick={()=>toggleSaved(tender.id)}>{saved?'★ Saved':'☆ Save tender'}</button><button className="primary">Analyze tender →</button></div></div></div>}
