import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const plans = [
  {name:'Free', price:'OMR 0', desc:'Explore Oman opportunities', features:['Limited tender feed','Basic search','5 saved tenders']},
  {name:'Starter', price:'OMR 9', desc:'For individual bidders', features:['Full tender search','Email deadline alerts','50 saved tenders','Basic company matching']},
  {name:'Pro', price:'OMR 25', desc:'For active contractors', featured:true, features:['AI tender summaries','Eligibility analysis','Personalized match score','Unlimited saved tenders','Priority alerts']},
  {name:'Business', price:'OMR 59', desc:'For tender teams', features:['Everything in Pro','Up to 10 users','Multiple company profiles','Exports & reports','Team workspace']}
];

const demoTenders = [
  {id:1,title:'Supply & Installation of Electrical Equipment',entity:'Public Authority for Special Economic Zones',category:'Electrical',location:'Duqm',deadline:'28 Sep 2026',value:'OMR 185,000',score:94,status:'Strong fit'},
  {id:2,title:'Building Maintenance & MEP Services',entity:'Government Services',category:'MEP / Maintenance',location:'Muscat',deadline:'02 Oct 2026',value:'OMR 420,000',score:88,status:'Strong fit'},
  {id:3,title:'Road Lighting Upgrade Works',entity:'Municipal Services',category:'Infrastructure',location:'Salalah',deadline:'07 Oct 2026',value:'OMR 760,000',score:81,status:'Good fit'},
  {id:4,title:'IT Network Security & Support Services',entity:'Government Technology',category:'IT / Security',location:'Muscat',deadline:'14 Oct 2026',value:'OMR 95,000',score:67,status:'Review'},
  {id:5,title:'HVAC Replacement and Preventive Maintenance',entity:'Public Utilities',category:'HVAC',location:'Sohar',deadline:'21 Oct 2026',value:'OMR 310,000',score:91,status:'Strong fit'}
];

function App(){
 const [view,setView]=useState('landing');
 const [saved,setSaved]=useState([]);
 const [profile,setProfile]=useState({company:'',sector:'',location:'Muscat',size:''});
 const [query,setQuery]=useState('');
 const [filter,setFilter]=useState('All');
 const filtered=useMemo(()=>demoTenders.filter(t=>(filter==='All'||t.category.includes(filter)) && (t.title+t.entity+t.category+t.location).toLowerCase().includes(query.toLowerCase())),[query,filter]);
 const start=()=>setView('onboarding');
 if(view==='onboarding') return <Onboarding profile={profile} setProfile={setProfile} onDone={()=>setView('dashboard')} />;
 if(view==='dashboard') return <Dashboard profile={profile} tenders={filtered} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} saved={saved} setSaved={setSaved} onHome={()=>setView('landing')} />;
 return <Landing onStart={start} />;
}

function Landing({onStart}){return <div className="app">
 <header className="nav"><div className="brand"><span className="mark">OT</span><span>Oman Tender <b>Intelligence</b></span></div><nav><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#how">How it works</a></nav><div className="actions"><button className="ghost">Sign in</button><button className="primary" onClick={onStart}>Start free</button></div></header>
 <main>
  <section className="hero"><div className="eyebrow">OMAN PROCUREMENT INTELLIGENCE</div><h1>Find the tenders<br/><span>worth bidding for.</span></h1><p>One focused workspace for Oman contractors to discover relevant tenders, understand requirements, and act before deadlines.</p><div className="heroBtns"><button className="primary big" onClick={onStart}>Start free →</button><a className="ghost big" href="#how">See how it works</a></div><div className="trust"><span>✓ Oman-focused</span><span>✓ Relevance scoring</span><span>✓ Deadline alerts</span><span>✓ AI analysis</span></div></section>
  <section className="stats"><div><strong>Live</strong><small>tender intelligence</small></div><div><strong>AI</strong><small>bid relevance scoring</small></div><div><strong>24/7</strong><small>deadline monitoring</small></div><div><strong>1</strong><small>workspace for your team</small></div></section>
  <section id="features" className="section"><div className="sectionHead"><div><div className="eyebrow">BUILT FOR CONTRACTORS</div><h2>From tender discovery<br/>to bid decision.</h2></div><p>Stop wasting hours scanning procurement portals. Get the opportunities that fit your business, with the context you need to decide.</p></div><div className="featureGrid"><Feature icon="◈" title="Personalized matching" text="Tell us your sectors, capabilities and preferred contract size. Every new tender gets a relevance score."/><Feature icon="⌕" title="Smart discovery" text="Search across your Oman tender sources from one clean workspace with practical filters."/><Feature icon="✦" title="AI tender analysis" text="Summarize scope, requirements, deadlines and eligibility before your team spends time on the documents."/><Feature icon="◷" title="Deadline intelligence" text="Keep critical submission dates visible and receive timely alerts for saved opportunities."/><Feature icon="▣" title="Company profile" text="Build a reusable company capability profile to improve recommendations and qualification checks."/><Feature icon="↗" title="Team workflow" text="Save, review and share opportunities with your tender team as the product grows."/></div></section>
  <section id="how" className="how"><div className="eyebrow">HOW IT WORKS</div><h2>Three steps to a smarter bid pipeline.</h2><div className="steps"><Step n="01" title="Create your company profile" text="Choose sectors, capabilities, locations and bid preferences."/><Step n="02" title="Get matched opportunities" text="New Oman tenders are scored against your profile so high-fit opportunities stand out."/><Step n="03" title="Analyze & act" text="Open the tender, review AI insights, save it and keep the deadline on your radar."/></div></section>
  <section id="pricing" className="pricing"><div className="eyebrow">SIMPLE PRICING</div><h2>Start free. Upgrade when<br/>tender volume grows.</h2><div className="plans">{plans.map(p=><div className={'plan '+(p.featured?'featured':'')} key={p.name}>{p.featured&&<div className="popular">MOST POPULAR</div>}<h3>{p.name}</h3><p>{p.desc}</p><div className="price">{p.price}<small>/ month</small></div><button onClick={onStart} className={p.featured?'primary':'outline'}>{p.name==='Free'?'Get started':'Choose '+p.name}</button><ul>{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul></div>)}</div></section>
  <section className="cta"><div><div className="eyebrow">READY TO BID BETTER?</div><h2>Put Oman tender intelligence<br/>to work for your company.</h2></div><button className="primary big" onClick={onStart}>Create free account →</button></section>
 </main><footer><span>© 2026 Oman Tender Intelligence</span><span>Commercial SaaS • Oman</span></footer>
 </div>}

function Onboarding({profile,setProfile,onDone}){const [step,setStep]=useState(1); const next=()=>step<2?setStep(2):onDone(); return <div className="shell"><div className="onboard"><div className="brand"><span className="mark">OT</span><span>Oman Tender <b>Intelligence</b></span></div><div className="progress"><span className={step>=1?'active':''}></span><span className={step>=2?'active':''}></span></div>{step===1?<><div className="eyebrow">STEP 1 OF 2</div><h1>Tell us about your company.</h1><p className="muted">This profile powers your tender matching score.</p><label>Company name<input value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})} placeholder="e.g. Al Noor Trading LLC"/></label><label>Primary sector<select value={profile.sector} onChange={e=>setProfile({...profile,sector:e.target.value})}><option value="">Select sector</option><option>Construction</option><option>Electrical</option><option>MEP / Maintenance</option><option>IT / Technology</option><option>Infrastructure</option><option>Trading / Supply</option></select></label></>:<><div className="eyebrow">STEP 2 OF 2</div><h1>Set your bid preferences.</h1><p className="muted">You can change these later.</p><label>Preferred location<select value={profile.location} onChange={e=>setProfile({...profile,location:e.target.value})}><option>Muscat</option><option>Duqm</option><option>Sohar</option><option>Salalah</option><option>All Oman</option></select></label><label>Typical contract size<select value={profile.size} onChange={e=>setProfile({...profile,size:e.target.value})}><option value="">Select range</option><option>Under OMR 100k</option><option>OMR 100k–500k</option><option>OMR 500k–1m</option><option>OMR 1m+</option></select></label></>}<button className="primary big full" onClick={next}>{step===1?'Continue →':'Open my dashboard →'}</button><button className="ghost full" onClick={onDone}>Skip for now</button></div></div>}

function Dashboard({profile,tenders,query,setQuery,filter,setFilter,saved,setSaved,onHome}){const toggle=id=>setSaved(saved.includes(id)?saved.filter(x=>x!==id):[...saved,id]);return <div className="dashboard"><aside><div className="brand"><span className="mark">OT</span><b>OT Intelligence</b></div><div className="sideNav"><button className="selected">▦ Overview</button><button>◈ Matched tenders</button><button>♡ Saved tenders <em>{saved.length}</em></button><button>◫ Deadlines</button><button>⚙ Company profile</button></div><div className="sideBottom"><div className="mini">{profile.company?.slice(0,1)||'C'}</div><div><b>{profile.company||'Your company'}</b><small>Pro trial workspace</small></div></div></aside><main className="dashMain"><header className="dashTop"><div><span className="eyebrow">TENDER PIPELINE</span><h1>Good morning{profile.company?', '+profile.company:''}.</h1></div><button className="outline" onClick={onHome}>View public site</button></header><div className="dashStats"><Stat label="Matched today" value="12" change="+4 new"/><Stat label="Strong fits" value="5" change="≥ 80% score"/><Stat label="Saved tenders" value={saved.length} change="Your watchlist"/><Stat label="Deadlines soon" value="3" change="Next 14 days"/></div><section className="tenderPanel"><div className="panelHead"><div><h2>Recommended tenders</h2><p>Ranked against your company profile.</p></div><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tenders..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Electrical</option><option>MEP</option><option>Infrastructure</option><option>IT</option><option>HVAC</option></select></div></div><div className="tenderList">{tenders.map(t=><article className="tender" key={t.id}><div className="score"><strong>{t.score}</strong><small>match</small></div><div className="tenderBody"><div className="tags"><span>{t.category}</span><span>{t.location}</span></div><h3>{t.title}</h3><p>{t.entity}</p><div className="meta"><span>Deadline <b>{t.deadline}</b></span><span>Est. value <b>{t.value}</b></span></div></div><div className="tenderActions"><button className={saved.includes(t.id)?'savedBtn':'outline'} onClick={()=>toggle(t.id)}>{saved.includes(t.id)?'✓ Saved':'♡ Save'}</button><button className="primary">Analyze</button></div></article>)}</div>{!tenders.length&&<div className="empty">No tenders match your search. Try another keyword or filter.</div>}</section></main></div>}

const Stat=({label,value,change})=><div className="dashStat"><small>{label}</small><strong>{value}</strong><span>{change}</span></div>;
const Feature=({icon,title,text})=><div className="feature"><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>;
const Step=({n,title,text})=><div className="step"><div className="num">{n}</div><h3>{title}</h3><p>{text}</p></div>;
createRoot(document.getElementById('root')).render(<App/>);
